# Generated by Django 4.2.5 on 2023-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_group_delete_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='display_text',
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
