# Generated by Django 4.2.5 on 2023-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, to='courses.question'),
        ),
    ]
