# Generated by Django 4.2.5 on 2023-10-06 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_image_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(default='default_image.jpg', max_length=255),
        ),
    ]
