# Generated by Django 4.2.5 on 2023-10-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_mymodel_remove_question_image_question_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image_url',
            new_name='image',
        ),
    ]
