# Generated by Django 4.2.5 on 2023-10-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
