# Generated by Django 4.2.5 on 2023-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_answer_selected_option_remove_answer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.URLField(default='default_image.jpg', max_length=255),
        ),
    ]
