# Generated by Django 4.2.5 on 2023-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_answer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
